// prettier-ignore
export const adjectives = [
  "abandoned", "ancient", "blazing", "bold", "brittle",
  "calm", "chaotic", "cheerful", "cloudy", "colossal",
  "crimson", "crooked", "cunning", "damp", "daring",
  "dazzling", "desolate", "distant", "dusty", "eager",
  "eerie", "elegant", "enormous", "faint", "ferocious",
  "flickering", "fragile", "frantic", "frozen", "fuzzy",
  "gentle", "ghostly", "gigantic", "glistening", "gloomy",
  "glorious", "golden", "grim", "hollow", "howling",
  "humble", "hushed", "icy", "immense", "impulsive",
  "jagged", "jolly", "keen", "lanky", "lavish",
  "listless", "lofty", "luminous", "lurking", "majestic",
  "murky", "mysterious", "narrow", "nimble", "obscure",
  "ancient", "pale", "peculiar", "phantom", "placid",
  "plush", "radiant", "ragged", "rapid", "reckless",
  "restless", "rigid", "roaring", "rugged", "rusty",
  "sacred", "savage", "scarlet", "serene", "shattered",
  "silent", "sinister", "sleek", "slender", "somber",
  "stormy", "stout", "strange", "swift", "tangled",
  "timid", "towering", "twisted", "vibrant", "vivid",
  "wandering", "weary", "whispering", "wild", "withered",
];

// prettier-ignore
export const nouns = [
  "anchor", "anvil", "abyss", "arrow", "atlas",
  "beacon", "blade", "blizzard", "boulder", "bridge",
  "canyon", "castle", "cavern", "chain", "cipher",
  "citadel", "cliff", "clock", "comet", "compass",
  "crater", "crown", "dagger", "delta", "desert",
  "dusk", "echo", "ember", "empire", "expedition",
  "fable", "falcon", "fissure", "flame", "forest",
  "fortress", "fountain", "fracture", "frontier", "frost",
  "gateway", "glacier", "globe", "gorge", "grave",
  "harbor", "harvest", "horizon", "hurricane", "island",
  "journal", "jungle", "labyrinth", "lantern", "legend",
  "lightning", "map", "marsh", "maze", "meadow",
  "mirror", "monument", "mountain", "nebula", "nomad",
  "oasis", "ocean", "orbit", "omen", "oracle",
  "peak", "phantom", "pilgrim", "pinnacle", "portal",
  "prism", "quarry", "quest", "raven", "reef",
  "refuge", "relic", "ridge", "ruin", "rune",
  "sanctuary", "shadow", "shipwreck", "shore", "signal",
  "specter", "spire", "storm", "temple", "throne",
  "tide", "torch", "tower", "valley", "vault",
  "vessel", "volcano", "voyage", "wilderness", "wraith",
];
