name: CI
on:
  push:
    branches: [master, web-modules]
  pull_request:
    branches: [master, web-modules]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - name: Run a multi-line script
        run: |
          npm install
          npm test -- --coverage
          npm run build
