name: CI
on:
  push:
    branches: [master, feature/*]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install and build
        run: |
          npm install
          npx nx lint
          npx nx test --run
          npx nx build
      - name: Archive production site
        uses: actions/upload-artifact@v3
        with:
          name: production-site
          path: build
