name: CI
on:
  push:
    branches: [master, feature/*]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install and build
        run: |
          npm install
          npx nx lint site
          npx nx test site --run
          npx nx build site
      - name: Archive production site
        uses: actions/upload-artifact@v3
        with:
          name: production-site
          path: packages/site/build
